/* tslint:disable */
/* eslint-disable */
/**
 * LatinoNetOnline.Backend.V1 v1
 * A application with Swagger, Swashbuckle, and API versioning.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lautaro.carro@latinonet.online
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

