name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Chackout
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build
      env:
        .CI: false
      run: npm run build
      
    - name: Deploy To GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        # Git branch where assets will be deployed
        target_branch: gh-pages
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
